### ISSUE TITLE
tutorials and examples

### ISSUE THREAD

**Issue by wangjiawen2013** [jamescauwelier/gnuplotter#1]
Hi,
I am very interested in this project, could you show some usage examples ?

**Comment by jamescauwelier** [comment]
Hi @wangjiawen2013! It's still a work in progress, but I aim for the interface to be more declarative.

You would define a custom plot like so:

```rust
#[derive(Clone, PartialEq, Eq, Debug, Default, Axis)]
pub struct XAxis
{
    label: Required<Label<X>>
}

#[derive(Clone, PartialEq, Eq, Debug, Default, Axis)]
pub struct YAxis
{
    label: Maybe<Label<Y>>
}

#[derive(Clone, PartialEq, Debug, Default, Plot)]
pub struct Plot2D {
    title: Maybe<Title>,
    x: XAxis,
    y: YAxis,
    series: Series<f64>
}
```

And usage might look like this:

```rust
    #[test]
    fn test_plotting_linear_and_exponential_series() {
        let mut plot = Plot2D::default();
        plot.x.label().update("label x".into());

        let mut linear_series = Serie::<f64>::new();
        let mut exponential_series = Serie::<f64>::new();
        for i in 0..10 {
            linear_series.add(i as f64);
            exponential_series.add((i*i) as f64);
        }
        plot.series.add(linear_series);
        plot.series.add(exponential_series);

        let commands = plot.as_commands().unwrap();

        assert_eq!(commands.len(), 3);
    }
```

Does that match your expectations or needs?

The main idea is not to strictly define the requirements of a plot beforehand and realize that needs are very individual (while still providing a utility interface over gnuplot to make it easier to use).

**Comment by wangjiawen2013** [comment]
thanks, how many kinds of plots does gnuplotter support now ? such as boxplot, heatmap, bar chart and so on

**Comment by jamescauwelier** [comment]
For now it’s just the one example. It’s a cery young library in alpha state. You’re welcome to collaborate if you can find yourself in the design goals?

**Comment by jamescauwelier** [comment]
You might want to add some examples of the plot you're after. Then, I can see whether those fit my personal goals for the library. Thank you for reaching out and taking some time to interact.
